# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage : "windows-latest"
  
variables:
- name: token
  value: token

steps:
- task: UiPathPack@2
  displayName: Pack test project
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/UiBankTestingItAutomation'
    outputType: 'Tests'
    orchestratorConnection: 'COE Orchestrator IT tenant'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathTest@2
  displayName: Run tests in project
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'COE Orchestrator IT tenant'
    testProjectPath: '$(Build.SourcesDirectory)/UiBankTestingItAutomation'
    environment: 'TestingAutomation'
    folderName: 'TestingCI'
    testReportDestination: '$(Build.ArtifactStagingDirectory)\Output'