# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage : "windows-latest"
  
variables:
- name: token
  value: token

steps:


- task: UiPathTest@2
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'COE Orchestrator IT tenant'
    testSet: 'UiBank calculator regression set'
    folderName: 'TestingCI'